As instituições financeiras incorrem em perdas significativas devido à inadimplência de empréstimos de veículos. Isso levou ao endurecimento da subscrição de empréstimos de veículos e ao aumento das taxas de rejeição de empréstimos de veículos. A necessidade de um melhor modelo de pontuação de risco de crédito também é levantada por essas instituições.

Isso justifica um estudo para estimar os determinantes da inadimplência de empréstimos de veículos. Uma instituição financeira contratou você para prever com precisão a probabilidade de o mutuário/mutuário inadimplir um empréstimo de veículo nas primeiras EMI (Prestações Mensais Equivalentes) na data de vencimento. As seguintes informações sobre o empréstimo e o mutuário são fornecidas nos conjuntos de dados:

Informações do mutuário (dados demográficos como idade, comprovante de identidade etc.)

Informações do empréstimo (detalhes de desembolso, relação empréstimo/valor etc.)

Dados e histórico do bureau (pontuação do bureau, número de contas ativas, status de outros empréstimos, histórico de crédito etc.)

Fazer isso garantirá que os clientes capazes de pagar não sejam rejeitados e determinantes importantes possam ser identificados, os quais podem ser usados ​​posteriormente para minimizar as taxas de inadimplência.

Nome da variável Descrição Sem nome: 2

0 UniqueID Identificador para clientes

1 loan_default Pagamento inadimplente no primeiro EMI na data de vencimento

2 disbursed_amount Valor do empréstimo desembolsado

3 asset_cost Custo do ativo

4 ltv Empréstimo para valor do ativo

5 branch_id Agência onde o empréstimo foi desembolsado

6 supplier_id Concessionária de veículos onde o empréstimo foi desembolsado

7 manufacturer_id Fabricante do veículo (Hero, Honda, TVS etc.)

8 Current_pincode Código PIN atual do cliente

9 Date.of.Birth Data de nascimento do cliente

10 Employment.Type Tipo de emprego do cliente (assalariado/autônomo)

11 DisbursalDate Data do desembolso

12 State_ID Estado do desembolso

13 Employee_code_ID Funcionário da organização que registrou o desembolso

14 MobileNo_Avl_Flag se o número do celular for foi compartilhado pelo cliente e então sinalizado como 1

15 Aadhar_flag se aadhar foi compartilhado pelo cliente e então sinalizado como 1

16 PAN_flag se pan foi compartilhado pelo cliente e então sinalizado como 1

17 VoterID_flag se voter foi compartilhado pelo cliente e então sinalizado como 1

18 Driving_flag se DL foi compartilhado pelo cliente e então sinalizado como 1

19 Passport_flag se passport foi compartilhado pelo cliente e então sinalizado como 1

20 PERFORM_CNS.SCORE Pontuação do Bureau

21 PERFORM_CNS.SCORE.DESCRIPTION Descrição da pontuação do Bureau

22 PRI.NO.OF.ACCTS contagem do total de empréstimos tomados pelo cliente no momento do desembolso As contas primárias são aquelas que o cliente tomou para seu uso pessoal

23 PRI.ACTIVE.ACCTS contagem de empréstimos ativos tomados pelo cliente no momento do desembolso

24 PRI.OVERDUE.ACCTS contagem de contas inadimplentes no momento do desembolso

25 PRI.CURRENT.BALANCE valor total do principal em aberto dos empréstimos ativos no momento do desembolso

26 PRI.SANCTIONED.AMOUNT valor total que foi sancionado para todos os empréstimos no momento do desembolso

27 PRI.DISBURSED.AMOUNT valor total que foi desembolsado para todos os empréstimos no momento do desembolso

28 SEC.NO.OF.ACCTS contagem do total de empréstimos tomados pelo cliente no momento do desembolso Contas secundárias são aquelas nas quais o cliente atua como co-solicitante ou garantidor

29 SEC.ACTIVE.ACCTS contagem de empréstimos ativos tomados pelo cliente no momento do desembolso

30 SEC.OVERDUE.ACCTS contagem de contas inadimplentes no momento do desembolso
31 SEC.CURRENT.BALANCE valor total do principal em aberto dos empréstimos ativos no momento do desembolso

32 SEC.SANCTIONED.AMOUNT valor total que foi sancionado para todos os empréstimos no momento do desembolso

33 SEC.DISBURSED.AMOUNT valor total que foi desembolsado para todos os empréstimos no momento do desembolso

34 PRIMARY.INSTAL.AMT EMI Valor do empréstimo principal

35 SEC.INSTAL.AMT EMI Valor do empréstimo secundário

36 NEW.ACCTS.IN.LAST.SIX.MONTHS Novos empréstimos tomados pelo cliente nos últimos 6 meses antes do desembolso

37 DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS Empréstimos inadimplentes nos últimos 6 meses

38 AVERAGE.ACCT.AGE Prazo médio do empréstimo

39 CREDIT.HISTORY.LENGTH Tempo desde o primeiro empréstimo

40 NO.OF_INQUIRIES Consultas feitas pelo cliente para empréstimos

In [ ]:
!pip install deep-translator
!pip install ydata_profiling

Requirement already satisfied: deep-translator in /usr/local/lib/python3.10/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from deep-translator) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.10/dist-packages (from deep-translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2024.8.30)
Requirement already satisfied: ydata_profiling in /usr/local/lib/python3.10/dist-packages (4.12.0)
Requirement already satisfied: scipy<1.14,>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (2.2.2)
Requirement already satisfied: matplotlib<3.10,>=3.5 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (3.8.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (2.9.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (3.1.4)
Requirement already satisfied: visions<0.7.7,>=0.7.5 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]<0.7.7,>=0.7.5->ydata_profiling) (0.7.6)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (4.66.6)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (4.4.1)
Requirement already satisfied: imagehash==4.3.1 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (1.8.1)
Requirement already satisfied: numba<1,>=0.56.0 in /usr/local/lib/python3.10/dist-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata_profiling) (1.7.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata_profiling) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<3.2,>=2.11.1->ydata_profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (4.55.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.10,>=3.5->ydata_profiling) (2.8.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba<1,>=0.56.0->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata_profiling) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata_profiling) (2024.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from phik<0.13,>=0.11.1->ydata_profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2->ydata_profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2->ydata_profiling) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2->ydata_profiling) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata_profiling) (2024.8.30)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.10/dist-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata_profiling) (24.2.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.10/dist-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata_profiling) (3.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib<3.10,>=3.5->ydata_profiling) (1.16.0)

In [ ]:
from deep_translator import GoogleTranslator
import pandas as pd

# Exemplo de DataFrame
data = {'observation': [
    'This is a loan application',
    'The customer has a good credit history',
    'The payment is overdue'
]}
df = pd.DataFrame(data)

# Traduzir a coluna para português
df['observacao_pt'] = df['observation'].apply(lambda x: GoogleTranslator(source='en', target='pt').translate(x))

# Exibir o DataFrame com a nova coluna traduzida
print(df)

                              observation  \
0              This is a loan application
1  The customer has a good credit history
2                  The payment is overdue

                               observacao_pt
0             Este é um pedido de empréstimo
1  O cliente tem um bom histórico de crédito
2                  O pagamento está atrasado

In [ ]:
import pandas as pd
import plotly.express as px
from ydata_profiling import ProfileReport
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

# Pasta onde você acredita que o arquivo está
folder_path = '/content/drive/My Drive/Colab Notebooks'

# Listar arquivos na pasta
print(os.listdir(folder_path))

['Notebooks', 'Projeto SPAM', 'CRM', 'Projeto Boston Housing', 'xx.old', 'Projeto MNIST - Classificar Imagens', 'score_credito', 'Cópia de Score_Credito.ipynb']

In [ ]:
import pandas as pd
# Ajustar o pandas para mostrar todas as colunas
pd.set_option('display.max_columns', None)

# Caminho completo do arquivo no Google Drive
file_path_test = '/content/drive/My Drive/Colab Notebooks/score_credito/loan-default/test.csv'
file_path_train = '/content/drive/My Drive/Colab Notebooks/score_credito/loan-default/train.csv'
file_path_dict = '/content/drive/My Drive/Colab Notebooks/score_credito/loan-default/data_dictionary.csv'

# Carregar o arquivo no DataFrame
loan_data_test  = pd.read_csv(file_path_test)
loan_data_train = pd.read_csv(file_path_train)
df_dict         = pd.read_csv(file_path_dict)

# Substituir pontos por underscores nos nomes das colunas
loan_data_test.columns  = loan_data_test.columns.str.replace(r'\.', '_', regex=True)
loan_data_train.columns = loan_data_train.columns.str.replace(r'\.', '_', regex=True)

# Concatenar
df =  loan_data_train # pd.concat([loan_data_test, loan_data_train], axis=0)

# Ajusta Dict das Vars
df_dict['Desc_Portugues'] = df_dict['Description'].apply(lambda x: GoogleTranslator(source='en', target='pt').translate(x))
df_dict['Variable Name'] = df_dict['Variable Name'].str.replace(r'\.', '_', regex=True)
df_dict = df_dict.loc[:,['Variable Name','Desc_Portugues']]

# Exibir as primeiras linhas do dataset
print(df.dtypes)
df.loc[:5,:]

UniqueID                                 int64
disbursed_amount                         int64
asset_cost                               int64
ltv                                    float64
branch_id                                int64
supplier_id                              int64
manufacturer_id                          int64
Current_pincode_ID                       int64
Date_of_Birth                           object
Employment_Type                         object
DisbursalDate                           object
State_ID                                 int64
Employee_code_ID                         int64
MobileNo_Avl_Flag                        int64
Aadhar_flag                              int64
PAN_flag                                 int64
VoterID_flag                             int64
Driving_flag                             int64
Passport_flag                            int64
PERFORM_CNS_SCORE                        int64
PERFORM_CNS_SCORE_DESCRIPTION           object
PRI_NO_OF_ACCTS                          int64
PRI_ACTIVE_ACCTS                         int64
PRI_OVERDUE_ACCTS                        int64
PRI_CURRENT_BALANCE                      int64
PRI_SANCTIONED_AMOUNT                    int64
PRI_DISBURSED_AMOUNT                     int64
SEC_NO_OF_ACCTS                          int64
SEC_ACTIVE_ACCTS                         int64
SEC_OVERDUE_ACCTS                        int64
SEC_CURRENT_BALANCE                      int64
SEC_SANCTIONED_AMOUNT                    int64
SEC_DISBURSED_AMOUNT                     int64
PRIMARY_INSTAL_AMT                       int64
SEC_INSTAL_AMT                           int64
NEW_ACCTS_IN_LAST_SIX_MONTHS             int64
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS      int64
AVERAGE_ACCT_AGE                        object
CREDIT_HISTORY_LENGTH                   object
NO_OF_INQUIRIES                          int64
loan_default                             int64
dtype: object

,UniqueID,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date_of_Birth,Employment_Type,DisbursalDate,State_ID,Employee_code_ID,MobileNo_Avl_Flag,Aadhar_flag,PAN_flag,VoterID_flag,Driving_flag,Passport_flag,PERFORM_CNS_SCORE,PERFORM_CNS_SCORE_DESCRIPTION,PRI_NO_OF_ACCTS,PRI_ACTIVE_ACCTS,PRI_OVERDUE_ACCTS,PRI_CURRENT_BALANCE,PRI_SANCTIONED_AMOUNT,PRI_DISBURSED_AMOUNT,SEC_NO_OF_ACCTS,SEC_ACTIVE_ACCTS,SEC_OVERDUE_ACCTS,SEC_CURRENT_BALANCE,SEC_SANCTIONED_AMOUNT,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,loan_default
0,420825,50578,58400,89.55,67,22807,45,1441,01-01-84,Salaried,03-08-18,6,1998,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
1,537409,47145,65550,73.23,67,22807,45,1502,31-07-85,Self employed,26-09-18,6,1998,1,1,0,0,0,0,598,I-Medium Risk,1,1,1,27600,50200,50200,0,0,0,0,0,0,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1
2,417566,53278,61360,89.63,67,22807,45,1497,24-08-85,Self employed,01-08-18,6,1998,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
3,624493,57513,66113,88.48,67,22807,45,1501,30-12-93,Self employed,26-10-18,6,1998,1,1,0,0,0,0,305,L-Very High Risk,3,0,0,0,0,0,0,0,0,0,0,0,31,0,0,0,0yrs 8mon,1yrs 3mon,1,1
4,539055,52378,60300,88.39,67,22807,45,1495,09-12-77,Self employed,26-09-18,6,1998,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,1,1
5,518279,54513,61900,89.66,67,22807,45,1501,08-09-90,Self employed,19-09-18,6,1998,1,1,0,0,0,0,825,A-Very Low Risk,2,0,0,0,0,0,0,0,0,0,0,0,1347,0,0,0,1yrs 9mon,2yrs 0mon,0,0

In [ ]:
# Visualisa Dict
df_dict

,Variable Name,Desc_Portugues
0,UniqueID,Identificador para clientes
1,loan_default,Inadimplência no primeiro EMI na data de venci...
2,disbursed_amount,Valor do empréstimo desembolsado
3,asset_cost,Custo do Ativo
4,ltv,Empréstimo para valor do ativo
5,branch_id,Agência onde o empréstimo foi desembolsado
6,supplier_id,Concessionária de veículos onde o empréstimo f...
7,manufacturer_id,"Fabricante de veículos (Hero, Honda, TVS etc.)"
8,Current_pincode,Código PIN atual do cliente
9,Date_of_Birth,Data de nascimento do cliente
10,Employment_Type,Tipo de emprego do cliente (assalariado/autônomo)
11,DisbursalDate,Data de desembolso
12,State_ID,Estado de desembolso
13,Employee_code_ID,Funcionário da organização que registrou o des...
14,MobileNo_Avl_Flag,se o número do celular foi compartilhado pelo ...
15,Aadhar_flag,"se aadhar foi compartilhado pelo cliente, entã..."
16,PAN_flag,"se a panela foi compartilhada pelo cliente, en..."
17,VoterID_flag,"se o eleitor foi compartilhado pelo cliente, e..."
18,Driving_flag,se DL foi compartilhado pelo cliente então sin...
19,Passport_flag,se o passaporte foi compartilhado pelo cliente...
20,PERFORM_CNS_SCORE,Pontuação do Bureau
21,PERFORM_CNS_SCORE_DESCRIPTION,Descrição da pontuação do Bureau
22,PRI_NO_OF_ACCTS,contagem do total de empréstimos tomados pelo ...
23,PRI_ACTIVE_ACCTS,contagem de empréstimos ativos tomados pelo cl...
24,PRI_OVERDUE_ACCTS,contagem de contas inadimplentes no momento do...
25,PRI_CURRENT_BALANCE,Valor total do principal em dívida dos emprést...
26,PRI_SANCTIONED_AMOUNT,valor total que foi sancionado para todos os e...
27,PRI_DISBURSED_AMOUNT,valor total que foi desembolsado para todos os...
28,SEC_NO_OF_ACCTS,contagem do total de empréstimos tomados pelo ...
29,SEC_ACTIVE_ACCTS,contagem de empréstimos ativos tomados pelo cl...
30,SEC_OVERDUE_ACCTS,contagem de contas inadimplentes no momento do...
31,SEC_CURRENT_BALANCE,Valor total do principal em dívida dos emprést...
32,SEC_SANCTIONED_AMOUNT,valor total que foi sancionado para todos os e...
33,SEC_DISBURSED_AMOUNT,valor total que foi desembolsado para todos os...
34,PRIMARY_INSTAL_AMT,Valor EMI do empréstimo principal
35,SEC_INSTAL_AMT,Valor EMI do empréstimo secundário
36,NEW_ACCTS_IN_LAST_SIX_MONTHS,Novos empréstimos tomados pelo cliente nos últ...
37,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,Empréstimos inadimplentes nos últimos 6 meses
38,AVERAGE_ACCT_AGE,Prazo médio do empréstimo
39,CREDIT_HISTORY_LENGTH,Tempo desde o primeiro empréstimo
40,NO_OF_INQUIRIES,Consultas feitas pelo cliente para empréstimos

# **Análise de IV & WOE**

# **Tratativas Pontuais e Formato das Variáves**

In [ ]:
import numpy as np

# Função para converter o formato 'Xyrs Ymon' em meses
def convert_to_months(history):
    # Verificar se o valor não é nulo e é uma string
    if isinstance(history, str):
        try:
            # Separar os componentes de anos e meses
            years, months = history.split(' ')
            years = int(years.replace('yrs', ''))  # Retirar 'yrs' e converter para inteiro
            months = int(months.replace('mon', ''))  # Retirar 'mon' e converter para inteiro

            # Calcular o total de meses
            total_months = years * 12 + months
            return total_months
        except ValueError:
            return np.nan  # Caso ocorra erro no formato
    return np.nan  # Se não for string, retornar np.nan

# Aplicar a função ao DataFrame
df['CREDIT_HISTORY_LENGTH'] = df['CREDIT_HISTORY_LENGTH'].apply(lambda x: convert_to_months(x))
df['AVERAGE_ACCT_AGE']      = df['AVERAGE_ACCT_AGE'].apply(lambda x: convert_to_months(x))

In [ ]:
dict_vars_formats = {
    'UniqueID': str,  # Identificador único
    'loan_default': int,  # Indicador de inadimplência (0/1)
    'disbursed_amount': float,  # Valor desembolsado
    'asset_cost': float,  # Custo do ativo
    'ltv': float,  # Loan-to-Value (relação do empréstimo com o valor do ativo)
    'branch_id': str,  # ID da agência
    'supplier_id': str,  # ID do fornecedor
    'manufacturer_id': str,  # ID do fabricante
    'Current_pincode': str,  # Código postal
    'Date_of_Birth': 'datetime64[ns]',  # Data de nascimento
    'Employment_Type': str,  # Tipo de emprego (ex.: "Salaried", "Self-employed")
    'DisbursalDate': 'datetime64[ns]',  # Data de desembolso
    'State_ID': str,  # ID do estado
    'Employee_code_ID': str,  # Código do funcionário
    'MobileNo_Avl_Flag': int,  # Flag para disponibilidade de número móvel
    'Aadhar_flag': int,  # Flag de Aadhar (documento de identificação na Índia)
    'PAN_flag': int,  # Flag de PAN (número de identificação fiscal na Índia)
    'VoterID_flag': int,  # Flag de Voter ID (identidade eleitoral)
    'Driving_flag': int,  # Flag de carteira de motorista
    'Passport_flag': int,  # Flag de passaporte
    'PERFORM_CNS_SCORE': int,  # Score CNS de desempenho
    'PERFORM_CNS_SCORE_DESCRIPTION': str,  # Descrição do score CNS
    'PRI_NO_OF_ACCTS': int,  # Número de contas principais
    'PRI_ACTIVE_ACCTS': int,  # Contas principais ativas
    'PRI_OVERDUE_ACCTS': int,  # Contas principais atrasadas
    'PRI_CURRENT_BALANCE': float,  # Saldo atual das contas principais
    'PRI_SANCTIONED_AMOUNT': float,  # Montante sancionado em contas principais
    'PRI_DISBURSED_AMOUNT': float,  # Montante desembolsado em contas principais
    'SEC_NO_OF_ACCTS': int,  # Número de contas secundárias
    'SEC_ACTIVE_ACCTS': int,  # Contas secundárias ativas
    'SEC_OVERDUE_ACCTS': int,  # Contas secundárias atrasadas
    'SEC_CURRENT_BALANCE': float,  # Saldo atual das contas secundárias
    'SEC_SANCTIONED_AMOUNT': float,  # Montante sancionado em contas secundárias
    'SEC_DISBURSED_AMOUNT': float,  # Montante desembolsado em contas secundárias
    'PRIMARY_INSTAL_AMT': float,  # Valor da parcela principal
    'SEC_INSTAL_AMT': float,  # Valor da parcela secundária
    'NEW_ACCTS_IN_LAST_SIX_MONTHS': int,  # Novas contas nos últimos 6 meses
    'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS': int,  # Contas inadimplentes nos últimos 6 meses
    'AVERAGE_ACCT_AGE': int,  # Idade média das contas (geralmente em formato "xY yM")
    'CREDIT_HISTORY_LENGTH': int,  # Duração do histórico de crédito (formato "xY yM")
    'NO_OF_INQUIRIES': int  # Número de consultas de crédito
}

# Ajusta Formatos
def ajustar_tipos(df, tipos_variaveis):
    df= df.copy()  # Garante que o DataFrame original não seja modificado
    for coluna, tipo in tipos_variaveis.items():
        if coluna in df.columns:
            if tipo == 'datetime64[ns]':  # Conversão para datas
                df[coluna] = pd.to_datetime(df[coluna], errors='coerce')
            else:
                try:
                    df[coluna] = df[coluna].astype(tipo)
                except Exception as e:
                    print(f"Erro ao converter coluna '{coluna}' para {tipo}: {e}")
    return df

# Aplicar o ajuste usando o dicionário `tipos_variaveis`
df = ajustar_tipos(df, dict_vars_formats)

# Verificar os tipos ajustados
print(df.dtypes)
df

<ipython-input-67-c6b33bc4b954>:51: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[coluna] = pd.to_datetime(df[coluna], errors='coerce')

UniqueID                                       object
disbursed_amount                              float64
asset_cost                                    float64
ltv                                           float64
branch_id                                      object
supplier_id                                    object
manufacturer_id                                object
Current_pincode_ID                              int64
Date_of_Birth                          datetime64[ns]
Employment_Type                                object
DisbursalDate                          datetime64[ns]
State_ID                                       object
Employee_code_ID                               object
MobileNo_Avl_Flag                               int64
Aadhar_flag                                     int64
PAN_flag                                        int64
VoterID_flag                                    int64
Driving_flag                                    int64
Passport_flag                                   int64
PERFORM_CNS_SCORE                               int64
PERFORM_CNS_SCORE_DESCRIPTION                  object
PRI_NO_OF_ACCTS                                 int64
PRI_ACTIVE_ACCTS                                int64
PRI_OVERDUE_ACCTS                               int64
PRI_CURRENT_BALANCE                           float64
PRI_SANCTIONED_AMOUNT                         float64
PRI_DISBURSED_AMOUNT                          float64
SEC_NO_OF_ACCTS                                 int64
SEC_ACTIVE_ACCTS                                int64
SEC_OVERDUE_ACCTS                               int64
SEC_CURRENT_BALANCE                           float64
SEC_SANCTIONED_AMOUNT                         float64
SEC_DISBURSED_AMOUNT                          float64
PRIMARY_INSTAL_AMT                            float64
SEC_INSTAL_AMT                                float64
NEW_ACCTS_IN_LAST_SIX_MONTHS                    int64
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS             int64
AVERAGE_ACCT_AGE                                int64
CREDIT_HISTORY_LENGTH                           int64
NO_OF_INQUIRIES                                 int64
loan_default                                    int64
dtype: object

<ipython-input-67-c6b33bc4b954>:51: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[coluna] = pd.to_datetime(df[coluna], errors='coerce')

,UniqueID,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date_of_Birth,Employment_Type,DisbursalDate,State_ID,Employee_code_ID,MobileNo_Avl_Flag,Aadhar_flag,PAN_flag,VoterID_flag,Driving_flag,Passport_flag,PERFORM_CNS_SCORE,PERFORM_CNS_SCORE_DESCRIPTION,PRI_NO_OF_ACCTS,PRI_ACTIVE_ACCTS,PRI_OVERDUE_ACCTS,PRI_CURRENT_BALANCE,PRI_SANCTIONED_AMOUNT,PRI_DISBURSED_AMOUNT,SEC_NO_OF_ACCTS,SEC_ACTIVE_ACCTS,SEC_OVERDUE_ACCTS,SEC_CURRENT_BALANCE,SEC_SANCTIONED_AMOUNT,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,loan_default
0,420825,50578.0,58400.0,89.55,67,22807,45,1441,1984-01-01,Salaried,2018-03-08,6,1998,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0
1,537409,47145.0,65550.0,73.23,67,22807,45,1502,1985-07-31,Self employed,2018-09-26,6,1998,1,1,0,0,0,0,598,I-Medium Risk,1,1,1,27600.0,50200.0,50200.0,0,0,0,0.0,0.0,0.0,1991.0,0.0,0,1,23,23,0,1
2,417566,53278.0,61360.0,89.63,67,22807,45,1497,1985-08-24,Self employed,2018-01-08,6,1998,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0
3,624493,57513.0,66113.0,88.48,67,22807,45,1501,1993-12-30,Self employed,2018-10-26,6,1998,1,1,0,0,0,0,305,L-Very High Risk,3,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,31.0,0.0,0,0,8,15,1,1
4,539055,52378.0,60300.0,88.39,67,22807,45,1495,1977-09-12,Self employed,2018-09-26,6,1998,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233149,626432,63213.0,105405.0,60.72,34,20700,48,1050,1988-01-08,Salaried,2018-10-26,6,3705,1,0,0,1,0,0,735,D-Very Low Risk,4,3,0,390443.0,416133.0,416133.0,0,0,0,0.0,0.0,0.0,4084.0,0.0,0,0,21,39,0,0
233150,606141,73651.0,100600.0,74.95,34,23775,51,990,1988-05-12,Self employed,2018-10-23,6,3705,1,0,0,1,0,0,825,A-Very Low Risk,1,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,1565.0,0.0,0,0,6,6,0,0
233151,613658,33484.0,71212.0,48.45,77,22186,86,2299,1976-01-06,Salaried,2018-10-24,4,3479,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0
233152,548084,34259.0,73286.0,49.10,77,22186,86,2299,1994-03-26,Salaried,2018-09-29,4,3479,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0
233153,630213,75751.0,116009.0,66.81,77,22186,86,2299,1984-02-18,Salaried,2018-10-27,4,3479,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0

In [ ]:
# Idade
df['idade'] = (((df['DisbursalDate'] - df['Date_of_Birth']).dt.days / 365).round()).astype(int)

In [ ]:
#  Quantidade de Classes em Categóricas
def qtd_class_vars_cat(df):
  # Criar um dicionário para armazenar o número de categorias
  category_counts = {}
  # Identificar colunas categóricas e contar categorias
  for column in df.select_dtypes(include=['object', 'category']):
      num_categories = df[column].nunique()  # Contar classes únicas
      category_counts[column] = num_categories  # Armazenar no dicionário

  # Ordenar o dicionário pelo número de categorias em ordem decrescente
  sorted_categories = sorted(category_counts.items(), key=lambda x: x[1], reverse=True)

  # Imprimir as variáveis e o número de categorias em ordem decrescente
  for column, num_categories in sorted_categories:
      print(f"Variável: {column}, Número de categorias: {num_categories}")

qtd_class_vars_cat(df)

# Define IDs e Drops
id_vars   = ['UniqueID', 'DisbursalDate', 'Employee_code_ID', 'supplier_id']
vars_drop = ['Date_of_Birth']

Variável: UniqueID, Número de categorias: 233154
Variável: Employee_code_ID, Número de categorias: 3270
Variável: supplier_id, Número de categorias: 2953
Variável: branch_id, Número de categorias: 82
Variável: State_ID, Número de categorias: 22
Variável: PERFORM_CNS_SCORE_DESCRIPTION, Número de categorias: 20
Variável: manufacturer_id, Número de categorias: 11
Variável: Employment_Type, Número de categorias: 3

In [ ]:
print(df['Employee_code_ID'].value_counts(normalize=True).sort_values(ascending=False).head(2)*100)
print(df['supplier_id'     ].value_counts(normalize=True).sort_values(ascending=False).head(2)*100)
print('')
print("Não var a pena trabalhar com essas variáveis, são ID's não utilizaveis pela falta de representatividade de alguma classe.")
print("Mas ainda assim manteremos ela mapeada com ID")

Employee_code_ID
2546    0.269350
620     0.215308
Name: proportion, dtype: float64
supplier_id
18317    0.614186
15694    0.557571
Name: proportion, dtype: float64

Não var a pena trabalhar com essas variáveis, são ID's não utilizaveis pela falta de representatividade de alguma classe.
Mas ainda assim manteremos ela mapeada com ID

In [ ]:
# Função de Agrupamento de Variáveis Categóricas
def agrupar_classes(df, column, threshold=0.05):
    """
    Ordena as classes de uma coluna em ordem decrescente de volumetria e agrupa classes com menos de 5% da volumetria em "Outros".

    Args:
        df (pd.DataFrame): O DataFrame que contém a coluna.
        column (str): O nome da coluna categórica/string a ser agrupada.
        threshold (float): O limite percentual para agrupar classes menores (padrão: 0.05 = 5%).

    Returns:
        pd.DataFrame: O DataFrame atualizado com as classes agrupadas.
    """
    df = df.copy()  # Garante que o DataFrame original não seja modificado
    # Calcular a distribuição percentual de cada classe
    class_distribution = df[column].value_counts(normalize=True)

    # Identificar classes com menos de "threshold" percentual
    minor_classes = class_distribution[class_distribution < threshold].index

    # Substituir as classes menores por "Outros"
    df[column] = df[column].apply(lambda x: "Outros" if x in minor_classes else x)

    '''# Reordenar as classes restantes em ordem decrescente de volumetria
    df[column] = pd.Categorical(df[column],
                                 categories=df[column].value_counts().index,
                                 ordered=True)'''
    return df

In [ ]:
# Para economizar tempo irei aplicar em todo dataframe. Mas na vida real salvamos a definição de "Outros" para aplciar em novos conjuntos
# Aqui iremos tentar aproveitar ao máximo as informações, transformando de forma coerente campos com muitas classes.
threshold_agrupamentos = 0.03
df['Employee_code_ID'] = agrupar_classes(df, column = 'Employee_code_ID', threshold=threshold_agrupamentos)['Employee_code_ID']
df['supplier_id']      = agrupar_classes(df, column = 'supplier_id'     , threshold=threshold_agrupamentos)['supplier_id']
df['branch_id']        = agrupar_classes(df, column = 'branch_id'       , threshold=threshold_agrupamentos)['branch_id']
df['State_ID']         = agrupar_classes(df, column = 'State_ID'        , threshold=threshold_agrupamentos)['State_ID']
df['PERFORM_CNS_SCORE_DESCRIPTION'] = agrupar_classes(df, column = 'PERFORM_CNS_SCORE_DESCRIPTION', threshold=threshold_agrupamentos)['PERFORM_CNS_SCORE_DESCRIPTION']
df['manufacturer_id']         = agrupar_classes(df, column = 'manufacturer_id'        , threshold=threshold_agrupamentos)['manufacturer_id']
qtd_class_vars_cat(df)

Variável: UniqueID, Número de categorias: 233154
Variável: State_ID, Número de categorias: 10
Variável: PERFORM_CNS_SCORE_DESCRIPTION, Número de categorias: 9
Variável: branch_id, Número de categorias: 8
Variável: manufacturer_id, Número de categorias: 7
Variável: Employment_Type, Número de categorias: 3
Variável: supplier_id, Número de categorias: 1
Variável: Employee_code_ID, Número de categorias: 1

In [ ]:
df.groupby('DisbursalDate')['DisbursalDate'].count()
max(df['DisbursalDate'])

Timestamp('2018-12-10 00:00:00')

# **Define Períodos Treino, Validação, Out-of-Time e Recente**

In [ ]:
# Certificando que DisbursalDate está no formato datetime
df['DisbursalDate'] = pd.to_datetime(df['DisbursalDate'], errors='coerce')

# Ordenar as datas para garantir que os intervalos estejam corretos
df = df.sort_values(by='DisbursalDate')

# Dividir em 3 intervalos de datas com volumes de casos iguais
df['Intervalo'] = pd.qcut(df['DisbursalDate'], q=3, labels=["Parte 1", "Parte 2", "Parte 3"])

# Exibir os resultados
print(df
 .groupby('Intervalo')
 .agg(
    min_date=('DisbursalDate', 'min'),
    max_date=('DisbursalDate', 'max'),
    target_rate=('loan_default', lambda x: (x == 1).mean())  # Calcula a taxa de target == 1
  )
)
del df['Intervalo']

            min_date   max_date  target_rate
Intervalo
Parte 1   2018-01-08 2018-08-31     0.212344
Parte 2   2018-09-08 2018-10-19     0.201480
Parte 3   2018-10-20 2018-12-10     0.237619

<ipython-input-74-05fc66f7aea5>:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby('Intervalo')

In [ ]:
#["Treino", "Validacao", "Out-of-Time"]
# Supondo que 'DisbursalDate' seja do tipo datetime
df['DisbursalDate'] = pd.to_datetime(df['DisbursalDate'])

'''# Função para determinar a semana dentro do mês
def get_week_of_month(date):
    # Primeiro dia do mês
    first_day = date.replace(day=1)
    # Determinar a semana do mês
    week_num = (date.day - 1) // 7 + 1
    # Garantir que a semana seja entre W1 e W4
    return f'W{week_num}'

# Criar a coluna 'Ano-Mês-Semana' no formato 'YYYY-MM-Ww'
df['Year_Month_Week'] = df['DisbursalDate'].dt.strftime('%Y-%m-') + df['DisbursalDate'].apply(get_week_of_month)
'''
# Criar a coluna 'Safra' no formato 'YYYYmm' como string
df['Safra'] = df['DisbursalDate'].dt.strftime('%Y%m')

# Exibir os resultados
df.groupby('Safra').agg(
    min_date    =('DisbursalDate', 'min'  ),
    max_date    =('DisbursalDate', 'max'  ),
    Volumetria  =('DisbursalDate', 'count'),
    target_rate =('loan_default' , lambda x: (x == 1).mean())  # Calcula a taxa de target == 1
)

         min_date   max_date  Volumetria  target_rate
Safra
201801 2018-01-08 2018-01-08        1708     0.229508
201802 2018-02-10 2018-02-10          25     0.080000
201803 2018-03-08 2018-03-10        5148     0.204740
201804 2018-04-08 2018-04-10        4627     0.214178
201805 2018-05-08 2018-05-10        2890     0.211419
201806 2018-06-08 2018-06-10        5991     0.215991
201807 2018-07-08 2018-07-09        4150     0.223614
201808 2018-08-08 2018-08-31       56975     0.211268
201809 2018-09-08 2018-09-30       54443     0.193468
201810 2018-10-08 2018-10-31       84875     0.240365
201811 2018-11-08 2018-11-10        6709     0.182591
201812 2018-12-08 2018-12-10        5613     0.203634

**Dividi da maneira acima para ficar mais parecedi com a realidade pratica, pois utilizamos os meses completos para desenvolver e validar. Assim, no preparamos para o efeito do tempo nas variáveis.
Note que temos a mesma taxa de maus ao longo do tempo, por conta disso está satisfatório no sentido da estratificação pelo target.**

# **Análise IV & WOE das Váriáveis**

In [ ]:
# @title Função IV & WOE - Renan Stolf Farhat
#### WOE and IV
#https://github.com/Sundar0989/WOE-and-IV/blob/master/WOE_IV.ipynb
#https://sundarstyles89.medium.com/weight-of-evidence-and-information-value-using-python-6f05072e83eb

# import packages
import pandas as pd
import numpy as np
# import pandas.core.algorithms as algos # indisponivel, usar numpy
from pandas import Series
import scipy.stats as stats
import re
import traceback
import string

max_bin   = 10
force_bin = 10

# define a binning function
def mono_bin(Y, X, n = max_bin):

    df1 = pd.DataFrame({"X": X, "Y": Y})
    justmiss = df1[['X','Y']][df1.X.isnull()]
    notmiss = df1[['X','Y']][df1.X.notnull()]
    r = 0
    while np.abs(r) < 1:
        try:
            d1 = pd.DataFrame({"X": notmiss.X, "Y": notmiss.Y, "Bucket": pd.qcut(notmiss.X, n)})
            d2 = d1.groupby('Bucket', as_index=True, observed=True)
            r, p = stats.spearmanr(d2.mean().X, d2.mean().Y)
            n = n - 1
        except Exception as e:
            n = n - 1

    if len(d2) == 1:
        n = force_bin
        bins = np.quantile(notmiss.X, np.linspace(0, 1, n))
        if len(np.unique(bins)) == 2:
            bins = np.insert(bins, 0, 1)
            bins[1] = bins[1]-(bins[1]/2)
        d1 = pd.DataFrame({"X": notmiss.X, "Y": notmiss.Y, "Bucket": pd.cut(notmiss.X, np.unique(bins),include_lowest=True)})
        d2 = d1.groupby('Bucket', as_index=True, observed=True)

    d3 = pd.DataFrame({},index=[])
    d3["MIN_VALUE"] = d2.min().X
    d3["MAX_VALUE"] = d2.max().X
    d3["COUNT"] = d2.count().Y
    d3["EVENT"] = d2.sum().Y
    d3["NONEVENT"] = d2.count().Y - d2.sum().Y
    d3=d3.reset_index(drop=True)

    if len(justmiss.index) > 0:
        d4 = pd.DataFrame({'MIN_VALUE':np.nan},index=[0])
        d4["MAX_VALUE"] = np.nan
        d4["COUNT"] = justmiss.count().Y
        d4["EVENT"] = justmiss.sum().Y
        d4["NONEVENT"] = justmiss.count().Y - justmiss.sum().Y
        d3 = pd.concat([d3, d4], ignore_index=True)

    d3["EVENT_RATE"] = d3.EVENT/d3.COUNT
    d3["NON_EVENT_RATE"] = d3.NONEVENT/d3.COUNT
    d3["DIST_EVENT"] = d3.EVENT/d3.sum().EVENT
    d3["DIST_NON_EVENT"] = d3.NONEVENT/d3.sum().NONEVENT
    d3["WOE"] = np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["IV_CLASS"] = (d3.DIST_EVENT-d3.DIST_NON_EVENT)*np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["VAR_NAME"] = "VAR"
    d3['CLASSE'] = (d3.reset_index()['index'] + 1).astype(str) + '. ' + '[' + d3['MIN_VALUE'].astype(str) + ' - ' + d3['MAX_VALUE'].astype(str) + ']'
    d3['CLASSE'] = d3['CLASSE'].astype(str)
    d3['MAX_VALUE'] = d3['MAX_VALUE'].astype(str)
    d3 = d3[['VAR_NAME', 'CLASSE', 'MIN_VALUE', 'MAX_VALUE', 'COUNT', 'EVENT', 'EVENT_RATE', 'NONEVENT', 'NON_EVENT_RATE', 'DIST_EVENT','DIST_NON_EVENT','WOE', 'IV_CLASS']]
    d3 = d3.replace([np.inf, -np.inf], 0)
    d3['IV'] = d3.IV_CLASS.sum()
    #d3['FPD1'] = d3['EVENT_RATE']
    d3["CUM_EVENT"] = d3["DIST_EVENT"].cumsum()
    d3["CUM_NON_EVENT"] = d3["DIST_NON_EVENT"].cumsum()
    d3["KS2"] = np.abs(d3["CUM_EVENT"] - d3["CUM_NON_EVENT"])
    d3["MAX_KS2"] = d3["KS2"].max()

    return(d3)

def char_bin(Y, X):

    df1 = pd.DataFrame({"X": X, "Y": Y})
    justmiss = df1[['X','Y']][df1.X.isnull()]
    notmiss = df1[['X','Y']][df1.X.notnull()]
    df2 = notmiss.groupby('X',as_index=True, observed=True)

    d3 = pd.DataFrame({},index=[])
    d3["COUNT"] = df2.count().Y
    d3["MIN_VALUE"] = df2.sum().Y.index
    d3["MAX_VALUE"] = d3["MIN_VALUE"]
    d3["EVENT"] = df2.sum().Y
    d3["NONEVENT"] = df2.count().Y - df2.sum().Y

    if len(justmiss.index) > 0:
        d4 = pd.DataFrame({'MIN_VALUE':'Missing'},index=[0])
        d4["MAX_VALUE"] = 'Missing'
        d4["COUNT"] = justmiss.count().Y
        d4["EVENT"] = justmiss.sum().Y
        d4["NONEVENT"] = justmiss.count().Y - justmiss.sum().Y
        d3 = pd.concat([d3, d4], ignore_index=True)

    d3["EVENT_RATE"] = d3.EVENT/d3.COUNT
    d3["NON_EVENT_RATE"] = d3.NONEVENT/d3.COUNT
    d3["DIST_EVENT"] = d3.EVENT/d3.sum().EVENT
    d3["DIST_NON_EVENT"] = d3.NONEVENT/d3.sum().NONEVENT
    d3["WOE"] = np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["IV_CLASS"] = (d3.DIST_EVENT-d3.DIST_NON_EVENT)*np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["VAR_NAME"] = "VAR"
    d3['CLASSE'] =  d3['MIN_VALUE']#.astype(str)
    d3 = d3[['VAR_NAME', 'CLASSE', 'MIN_VALUE', 'MAX_VALUE', 'COUNT', 'EVENT', 'EVENT_RATE', 'NONEVENT', 'NON_EVENT_RATE', 'DIST_EVENT','DIST_NON_EVENT','WOE', 'IV_CLASS']]
    d3 = d3.replace([np.inf, -np.inf], 0)
    d3['IV'] = d3.IV_CLASS.sum()
    #d3['FPD1'] = d3['EVENT_RATE']
    d3["CUM_EVENT"] = d3["DIST_EVENT"].cumsum()
    d3["CUM_NON_EVENT"] = d3["DIST_NON_EVENT"].cumsum()
    d3["KS2"] = np.abs(d3["CUM_EVENT"] - d3["CUM_NON_EVENT"])
    d3["MAX_KS2"] = d3["KS2"].max()
    d3 = d3.reset_index(drop = True)#.rename(columns={'index': 'RANK'})

    return(d3)

def data_vars(df1, target):

    stack = traceback.extract_stack()
    filename, lineno, function_name, code = stack[-2]
    #vars_name = re.compile(r'\((.*?)\).*$').search(code).groups()[0]
    #final = (re.findall(r"[\w']+", vars_name))[-1]
    final ='user_ns' ## comentar

    x = df1.dtypes.index
    count = -1

    for i in x:
        #print(i)
        if i.upper() not in (final.upper()):
            if np.issubdtype(df1[i], np.number) and len(Series.unique(df1[i])) > 2:
                conv = mono_bin(target, df1[i])
                conv["VAR_NAME"] = i
                conv["RANK"] = conv.reset_index(drop = False)['index'] + 1
                count = count + 1
            else:
                conv = char_bin(target, df1[i])
                conv["VAR_NAME"] = i
                conv["RANK"] = conv["CLASSE"]
                count = count + 1

            if count == 0:
                iv_df = conv
            else:
                #conv["RANK"] = conv.reset_index(drop = False)['index'] + 1
                iv_df = pd.concat([iv_df, conv], ignore_index=True) # True

    iv = pd.DataFrame({'IV':iv_df.groupby('VAR_NAME').IV.max()})
    iv = iv.reset_index()
    return(iv_df,iv)


#final_iv, IV = data_vars(finalDf.drop(targets, axis = 1),finalDf.cd_over60_mob6.astype(int)) # d2 = d1.groupby('Bucket', as_index=True)
#final_iv

In [ ]:
safras = list(df['Safra'].unique())
final_iv_safras = pd.DataFrame()
#IV_safras = pd.DataFrame()
for safra in safras:
  df_safra = df[df['Safra'] == safra].copy()
  print(safra)
  print(df_safra.shape)
  final_iv, IV = data_vars(df_safra.drop(['loan_default'] + id_vars + vars_drop, axis = 1)
                          ,df_safra.loan_default.astype(int)
                          )
  final_iv_safras = pd.concat([final_iv_safras, final_iv], ignore_index=True)
  #IV_safras = pd.concat([IV_safras, IV], ignore_index=True)

print(IV.sort_values(by='IV', ascending=False).iloc[:10,:])
final_iv_safras

201801
(1708, 43)
201802
(25, 43)

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

201803
(5148, 43)

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

201804
(4627, 43)
201805
(2890, 43)

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

201806
(5991, 43)

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

201807
(4150, 43)
201808
(56975, 43)
201809
(54443, 43)
201810
(84875, 43)
201811
(6709, 43)
201812
(5613, 43)

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

                         VAR_NAME        IV
33               disbursed_amount  0.056094
35                            ltv  0.049136
12  PERFORM_CNS_SCORE_DESCRIPTION  0.043689
29                       State_ID  0.042332
11              PERFORM_CNS_SCORE  0.036478
32                      branch_id  0.028725
0                AVERAGE_ACCT_AGE  0.024526
3              Current_pincode_ID  0.022252
17                PRI_NO_OF_ACCTS  0.022003
30                   VoterID_flag  0.021766

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [ ]:
final_iv_safras.loc[final_iv['VAR_NAME'] =='manufacturer_id']

,VAR_NAME,CLASSE,MIN_VALUE,MAX_VALUE,COUNT,EVENT,EVENT_RATE,NONEVENT,NON_EVENT_RATE,DIST_EVENT,DIST_NON_EVENT,WOE,IV_CLASS,IV,CUM_EVENT,CUM_NON_EVENT,KS2,MAX_KS2,RANK
48,manufacturer_id,120,120,120,78,17,0.217949,61,0.782051,0.043367,0.046353,-0.066570,0.000199,0.015454,0.043367,0.046353,2.985237e-03,0.022471,120
49,manufacturer_id,45,45,45,370,90,0.243243,280,0.756757,0.229592,0.212766,0.076110,0.001281,0.015454,0.272959,0.259119,1.384064e-02,0.022471,45
50,manufacturer_id,48,48,48,134,32,0.238806,102,0.761194,0.081633,0.077508,0.051853,0.000214,0.015454,0.354592,0.336626,1.796570e-02,0.022471,48
51,manufacturer_id,49,49,49,57,9,0.157895,48,0.842105,0.022959,0.036474,-0.462886,0.006256,0.015454,0.377551,0.373100,4.450716e-03,0.022471,49
52,manufacturer_id,51,51,51,149,37,0.248322,112,0.751678,0.094388,0.085106,0.103509,0.000961,0.015454,0.471939,0.458207,1.373209e-02,0.022471,51
53,manufacturer_id,67,67,67,19,7,0.368421,12,0.631579,0.017857,0.009119,0.672094,0.005873,0.015454,0.489796,0.467325,2.247069e-02,0.022471,67
54,manufacturer_id,86,86,86,896,200,0.223214,696,0.776786,0.510204,0.528875,-0.035942,0.000671,0.015454,1.000000,0.996201,3.799392e-03,0.022471,86
55,manufacturer_id,Outros,Outros,Outros,5,0,0.000000,5,1.000000,0.000000,0.003799,0.000000,0.000000,0.015454,1.000000,1.000000,2.220446e-16,0.022471,Outros

In [ ]:
# @title Salva Dados da Análise das Variáveis e Missing
from google.colab import files
# Salvar o DataFrame como CSV
final_iv.to_csv('Analise_IV_WOE_KS_Variaveis.csv', index=False)

## Fazer o download do arquivo
#files.download('Analise_IV_WOE_KS_Variaveis.csv')

In [ ]:
df.iloc[:5,:]

,UniqueID,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date_of_Birth,Employment_Type,DisbursalDate,State_ID,Employee_code_ID,MobileNo_Avl_Flag,Aadhar_flag,PAN_flag,VoterID_flag,Driving_flag,Passport_flag,PERFORM_CNS_SCORE,PERFORM_CNS_SCORE_DESCRIPTION,PRI_NO_OF_ACCTS,PRI_ACTIVE_ACCTS,PRI_OVERDUE_ACCTS,PRI_CURRENT_BALANCE,PRI_SANCTIONED_AMOUNT,PRI_DISBURSED_AMOUNT,SEC_NO_OF_ACCTS,SEC_ACTIVE_ACCTS,SEC_OVERDUE_ACCTS,SEC_CURRENT_BALANCE,SEC_SANCTIONED_AMOUNT,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,loan_default,idade
0,420825,50578.0,58400.0,89.55,67,Outros,45,1441,1984-01-01,Salaried,2018-03-08,6,Outros,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,34
1,537409,47145.0,65550.0,73.23,67,Outros,45,1502,1985-07-31,Self employed,2018-09-26,6,Outros,1,1,0,0,0,0,598,I-Medium Risk,1,1,1,27600.0,50200.0,50200.0,0,0,0,0.0,0.0,0.0,1991.0,0.0,0,1,23,23,0,1,33
2,417566,53278.0,61360.0,89.63,67,Outros,45,1497,1985-08-24,Self employed,2018-01-08,6,Outros,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,32
3,624493,57513.0,66113.0,88.48,67,Outros,45,1501,1993-12-30,Self employed,2018-10-26,6,Outros,1,1,0,0,0,0,305,Outros,3,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,31.0,0.0,0,0,8,15,1,1,25
4,539055,52378.0,60300.0,88.39,67,Outros,45,1495,1977-09-12,Self employed,2018-09-26,6,Outros,1,1,0,0,0,0,0,No Bureau History Available,0,0,0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,1,41

In [ ]:
X = loan_data_train.drop(['loan_default'], axis = 1).copy()['CREDIT_HISTORY_LENGTH']
Y = loan_data_train.loan_default.astype(int).copy()


df1 = pd.DataFrame({"X": X, "Y": Y})
justmiss = df1[['X','Y']][df1.X.isnull()]
notmiss = df1[['X','Y']][df1.X.notnull()]
df2 = notmiss.groupby('X',as_index=True)

d3 = pd.DataFrame({},index=[])
d3["COUNT"] = df2.count().Y
d3["MIN_VALUE"] = df2.sum().Y.index
d3["MAX_VALUE"] = d3["MIN_VALUE"]
d3["EVENT"] = df2.sum().Y
d3["NONEVENT"] = df2.count().Y - df2.sum().Y
d3
if len(justmiss.index) > 0:
    d4 = pd.DataFrame({'MIN_VALUE':'Missing'},index=[0])
    d4["MAX_VALUE"] = 'Missing'
    d4["COUNT"] = justmiss.count().Y
    d4["EVENT"] = justmiss.sum().Y
    d4["NONEVENT"] = justmiss.count().Y - justmiss.sum().Y
    d3 = pd.concat([d3, d4], ignore_index=True)

d3["EVENT_RATE"] = d3.EVENT/d3.COUNT
d3["NON_EVENT_RATE"] = d3.NONEVENT/d3.COUNT
d3["DIST_EVENT"] = d3.EVENT/d3.sum().EVENT
d3["DIST_NON_EVENT"] = d3.NONEVENT/d3.sum().NONEVENT
d3["WOE"] = np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
d3["IV_CLASS"] = (d3.DIST_EVENT-d3.DIST_NON_EVENT)*np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
d3["VAR_NAME"] = "VAR"
d3['CLASSE'] =  d3['MIN_VALUE']#.astype(str)
d3 = d3[['VAR_NAME', 'CLASSE', 'MIN_VALUE', 'MAX_VALUE', 'COUNT', 'EVENT', 'EVENT_RATE', 'NONEVENT', 'NON_EVENT_RATE', 'DIST_EVENT','DIST_NON_EVENT','WOE', 'IV_CLASS']]
d3 = d3.replace([np.inf, -np.inf], 0)
d3['IV'] = d3.IV_CLASS.sum()
#d3['FPD1'] = d3['EVENT_RATE']
d3 = d3.reset_index(drop = True)#.rename(columns={'index': 'RANK'})
d3

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,VAR_NAME,CLASSE,MIN_VALUE,MAX_VALUE,COUNT,EVENT,EVENT_RATE,NONEVENT,NON_EVENT_RATE,DIST_EVENT,DIST_NON_EVENT,WOE,IV_CLASS,IV
0,VAR,0yrs 0mon,0yrs 0mon,0yrs 0mon,119127,27572,0.231450,91555,0.768550,0.544783,0.501553,0.082678,3.574132e-03,0.020789
1,VAR,0yrs 10mon,0yrs 10mon,0yrs 10mon,2367,455,0.192226,1912,0.807774,0.008990,0.010474,-0.152791,2.267575e-04,0.020789
2,VAR,0yrs 11mon,0yrs 11mon,0yrs 11mon,2627,544,0.207080,2083,0.792920,0.010749,0.011411,-0.059798,3.960796e-05,0.020789
3,VAR,0yrs 1mon,0yrs 1mon,0yrs 1mon,1853,460,0.248246,1393,0.751754,0.009089,0.007631,0.174828,2.548743e-04,0.020789
4,VAR,0yrs 2mon,0yrs 2mon,0yrs 2mon,1977,432,0.218513,1545,0.781487,0.008536,0.008464,0.008463,6.087981e-07,0.020789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,VAR,9yrs 5mon,9yrs 5mon,9yrs 5mon,72,12,0.166667,60,0.833333,0.000237,0.000329,-0.326621,2.991427e-05,0.020789
290,VAR,9yrs 6mon,9yrs 6mon,9yrs 6mon,81,15,0.185185,66,0.814815,0.000296,0.000362,-0.198788,1.295706e-05,0.020789
291,VAR,9yrs 7mon,9yrs 7mon,9yrs 7mon,96,16,0.166667,80,0.833333,0.000316,0.000438,-0.326621,3.988569e-05,0.020789
292,VAR,9yrs 8mon,9yrs 8mon,9yrs 8mon,87,12,0.137931,75,0.862069,0.000237,0.000411,-0.549765,9.552683e-05,0.020789
293,VAR,9yrs 9mon,9yrs 9mon,9yrs 9mon,80,12,0.150000,68,0.850000,0.000237,0.000373,-0.451784,6.117717e-05,0.020789